version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=biscuit
      - POSTGRES_DB=biscuit
  memcached:
    image: memcached:latest
  app:
    build: .
    image: biscuitsis/biscuit
    volumes:
      - biscuit_media:/srv/media
      - biscuit_static:/srv/static
      - biscuit_backups:/var/backups/biscuit
      - biscuit_config:/etc/biscuit
    environment:
      - BISCUIT_http__allowed_hosts="['*']"
      - BISCUIT_caching__memcached__address=memcached:11211
      - POSTGRES_HOST=db
    depends_on:
      - db
      - memcached
  web:
    build: ./docker/nginx
    image: biscuitsis/biscuit-nginx
    volumes:
      - biscuit_media:/srv/media
      - biscuit_static:/srv/static
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  postgres_data:
  biscuit_media:
  biscuit_static:
  biscuit_backups:
  biscuit_config:
