version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aleksis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-aleksis}
      - POSTGRES_DB=aleksis
  redis:
    image: redis:latest
  app:
    build: ./docker/app
    image: registry.edugit.org/aleksis/official/aleksis:${ALEKSIS_IMAGE_TAG:-latest}
    volumes:
      - aleksis_media: /var/lib/aleksis/media/
      - aleksis_backups: /var/lib/aleksis/backups/
    environment:
      - ALEKSIS_http__allowed_hosts="['*']"
      - ALEKSIS_redis__host=redis
      - ALEKSIS_database__host=db
      - ALEKSIS_database__password=${POSTGRES_PASSWORD:-aleksis}
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - PREPARE=1
    ports:
      - 8000:80
    depends_on:
      - db
      - redis
  worker:
    build: .
    image: registry.edugit.org/aleksis/official/aleksis:${ALEKSIS_IMAGE_TAG:-latest}
    volumes:
      - aleksis_media: /var/lib/aleksis/media/
      - aleksis_backups: /var/lib/aleksis/backups/
    command: celery_worker
    environment:
      - ALEKSIS_redis__host=redis
      - ALEKSIS_database__host=db
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - PREPARE=0
      - RUN_MODE=celery-worker
    depends_on:
      - app
  scheduler:
    build: .
    image: registry.edugit.org/aleksis/official/aleksis:${ALEKSIS_IMAGE_TAG:-latest}
    command: celery_beat
    environment:
      - ALEKSIS_redis__host=redis
      - ALEKSIS_database__host=db
      - ALEKSIS_maintenance__debug=${ALEKSIS_maintenance__debug:-false}
      - PREPARE=0
      - RUN_MODE=celery-beat
    depends_on:
      - app
volumes:
  postgres_data:
  aleksis_media:
  aleksis_backups:
