[tool.poetry]
name = "BiscuIT-ng"
version = "1.0a4.dev0"
packages = [
    { include = "biscuit" }
]
readme = "README.rst"

description = "BiscuIT School Information System (SIS) - Next Generation Platform"
authors = ["Dominik George <dominik.george@teckids.org>", "mirabilos <thorsten.glaser@teckids.org>", "Tom Teichler <tom.teichler@teckids.org>"]
license = "EUPL-1.2"
homepage = "https://biscuit.edugit.io/"
repository = "https://edugit.org/BiscuIT/BiscuIT-ng"
documentation = "https://biscuit.edugit.io/BiscuIT-ng/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2"
django-any-js = "^1.0"
django-bootstrap4 = "^1.0"
django-fa = "^1.0"
django-debug-toolbar = "^2.0"
django-easy-audit = "^1.1"
django-middleware-global-request = "^0.1.2"
django-menu-generator = "^1.0.4"
django-tables2 = "^2.1"
Pillow = "^6.1"
django-phonenumber-field = {version = "^3.0", extras = ["phonenumbers"]}
django-sass-processor = "^0.7.3"
libsass = "^0.19.2"
colour = "^0.1.5"
dynaconf = {version = "^2.0", extras = ["yaml", "toml", "ini"]}
django-settings-context-processor = "^0.2"
django-auth-ldap = { version = "^2.0", optional = true }
django-maintenance-mode = "^0.13.3"
django-ipware = "^2.1"
easy-thumbnails = "^2.6"
django-image-cropping = "^1.2"
django-contact-form = "^1.7"
django-impersonate = "^1.4"
python-memcached = "^1.59"
django-dbbackup = "^3.2"
django-cron = "^0.5.1"
django-hattori = "^0.2"
psycopg2 = "^2.8"
django_select2 = "^7.1"
requests = "^2.22"
django-formtools = "^2.1"
django-otp = { version = "^0.7.4", optional = true }
django-two-factor-auth = { version = "^1.9", optional = true }
django-otp-yubikey = { version = '^0.5.2', optional = true }
twilio = { version = "^6.33", optional = true }

[tool.poetry.extras]
ldap = ["django-auth-ldap"]
2fa = ["django-otp", "django-two-factor-auth"]
twilio = ["twilio"]
yubikey = ["django-otp-yubikey"]

[tool.poetry.dev-dependencies]
sphinx = "^2.1"
sphinxcontrib-django = "^0.5.0"
sphinx-autodoc-typehints = "^1.7"
autopep8 = "^1.4"
pylama = "^7.7"
radon = "^3.0"
mypy = "^0.720.0"
django-stubs = "^1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
