[tool.poetry]
name = "BiscuIT-ng"
version = "1.0dev0"
description = "BiscuIT School Information System (SIS) - Next Generation Platform"
authors = ["BiscuIT Team <biscuit-dev@lists.teckids.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2"
django-any-js = "^1.0"
django-bootstrap4 = "^0.0.8"
django-fa = "^1.0"
django-easy-audit = "^1.1"
django-middleware-global-request = "^0.1.2"
django-simple-menu = "^1.2"
django-tables2 = "^2.1"
Pillow = "^6.1"
django-phonenumber-field = {version = "^3.0", extras = ["phonenumbers"]}
django-local-settings = {version = "^1.0-alpha.1", allows-prereleases = true}


[tool.poetry.dev-dependencies]
sphinx = "^2.1"
sphinxcontrib-django = "^0.5.0"
sphinx-autodoc-typehints = "^1.7"
recommonmark = "^0.6.0"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
