[tool.poetry]
name = "BiscuIT-ng"
version = "1.0dev0"
description = "BiscuIT School Information System (SIS) - Next Generation Platform"
authors = ["BiscuIT Team <biscuit-dev@lists.teckids.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
