docker_image:
  interruptible: true
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" >/kaniko/.docker/config.json
    - f=$(echo dist/$CI_PROJECT_NAME-*.tar.gz); f=${f#dist/$CI_PROJECT_NAME-}; f=${f%.tar.gz}; echo $f >app_version
    - /kaniko/executor
       --context $CI_PROJECT_DIR
       --dockerfile $CI_PROJECT_DIR/Dockerfile
       --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
       --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
       --build-arg APP_VERSION===$(cat app_version)
       --cache=true
       --cleanup
