review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review
  image: lwolf/helm-kubectl-docker
  script:
    - helm pull https://edugit.org/AlekSIS/Deployment/AlekSIS-k8s/-/archive/master/AlekSIS-k8s-master.tar.gz --untar
    - cd aleksis/
    - helm dep update
    - if helm get all $CI_ENVIRONMENT_SLUG >/dev/null 2>&1; then
       redisPassword=$(kubectl --namespace default get secret aleksis-test-redis -o jsonpath='{.data.redis-password}' | base64 -d);
       adminPassword=$(kubectl --namespace default get secret aleksis-test-aleksistest-postgresql='{.data.admin-password}' | base64 -d);
       postgresqlPassword=$(kubectl --namespace default get secret aleksis-test-postgresql -o jsonpath='{.data.postgresql-password}' | base64 -d);
       postgresPassword=$(kubectl --namespace default get secret aleksis-test-postgresql -o jsonpath='{.data.postgresql-postgres-password}' | base64 -d);
       secretKey=$(kubectl --namespace default get secret aleksis-test-aleksis -o jsonpath='{.data.secret-key}' | base64 -d);
       ADDITIONAL_SETS="
        --set postgresql.postgres.postgresPassword=$postgresPassword
        --set postgresql.postgresqlPassword=$postgresqlPassword
        --set redis.password=$redisPassword
        --set aleksis.secretKey=$secretKey
        --set aleksis.adminPassword=$adminPassword
       "
      fi
    - helm upgrade --install $CI_ENVIRONMENT_SLUG ./
       --set image.repository=$CI_REGISTRY_IMAGE
       --set image.tag=$CI_COMMIT_REF_SLUG
       --set ingress.domain=$KUBE_INGRESS_BASE_DOMAIN
       --set podAnnotations.'app\.gitlab\.com'/env=$CI_ENVIRONMENT_SLUG
       --set podAnnotations.'app\.gitlab\.com'/app=$CI_PROJECT_PATH_SLUG
       $ADDITIONAL_SETS
    - kubectl get secret $CI_ENVIRONMENT_SLUG-aleksis >../passwords.json
  artifacts:
    paths:
      - passwords.json
  rules:
    - if: $CI_MERGE_REQUEST_ID

stop_review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  variables:
    GIT_STRATEGY: none
  image: lwolf/helm-kubectl-docker
  script:
    - helm uninstall $CI_ENVIRONMENT_SLUG
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
