review:
  interruptible: true
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review
  image: lwolf/helm-kubectl-docker
  before_script:
    - apk add jq
  script:
    - helm pull https://edugit.org/AlekSIS/Official/AlekSIS-k8s/-/archive/master/AlekSIS-k8s-master.tar.gz --untar
    - cd aleksis/
    - helm dep update
    - if helm get all $CI_ENVIRONMENT_SLUG >/dev/null 2>&1; then
       adminPassword=$(kubectl get secret $CI_ENVIRONMENT_SLUG-aleksis -o jsonpath='{.data.admin-password}' | base64 -d);
       postgresPassword=$(kubectl get secret $CI_ENVIRONMENT_SLUG-postgresql -o jsonpath='{.data.postgresql-postgres-password}' | base64 -d);
       postgresqlPassword=$(kubectl get secret $CI_ENVIRONMENT_SLUG-postgresql -o jsonpath='{.data.postgresql-password}' | base64 -d);
       redisPassword=$(kubectl get secret $CI_ENVIRONMENT_SLUG-redis -o jsonpath='{.data.redis-password}' | base64 -d);
       secretKey=$(kubectl get secret $CI_ENVIRONMENT_SLUG-aleksis -o jsonpath='{.data.secret-key}' | base64 -d);
       ADDITIONAL_SETS="
        --set aleksis.config.maintenance.debug=true
        --set aleksis.adminPassword=$adminPassword
        --set aleksis.secretKey=$secretKey
        --set postgresql.postgresqlPassword=$postgresqlPassword
        --set postgresql.postgresqlPostgresPassword=$postgresPassword
        --set redis.password=$redisPassword
       ";
      fi
    - helm upgrade --install $CI_ENVIRONMENT_SLUG ./
       --set image.repository=$CI_REGISTRY_IMAGE
       --set image.tag=$CI_COMMIT_SHORT_SHA
       --set ingress.domain=$KUBE_INGRESS_BASE_DOMAIN
       --set podAnnotations.'app\.gitlab\.com'/env=$CI_ENVIRONMENT_SLUG
       --set podAnnotations.'app\.gitlab\.com'/app=$CI_PROJECT_PATH_SLUG
       $ADDITIONAL_SETS
    - kubectl get secret $CI_ENVIRONMENT_SLUG-aleksis -o jsonpath='{.data}' | jq 'map_values(@base64d)' >../passwords.json
  artifacts:
    paths:
      - passwords.json
  when: manual

stop_review:
  stage: deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  variables:
    GIT_STRATEGY: none
  image: lwolf/helm-kubectl-docker
  script:
    - helm uninstall $CI_ENVIRONMENT_SLUG
  when: manual
