image: registry.edugit.org/teckids/team-sysadmin/docker-images/python-pimped:latest

stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  FF_NETWORK_PER_BUILD: "true"
  POETRY_REPOSITORIES_GITLAB_URL: "$CI_API_V4_URL/projects/460/packages/pypi"
  POETRY_HTTP_BASIC_GITLAB_USERNAME: aleksis
  POETRY_HTTP_BASIC_GITLAB_PASSWORD: "$ALEKSIS_PUSH_TOKEN"
  POETRY_PYPI_TOKEN_PYPI: "$ALEKSIS_PUSH_TOKEN"

cache:
  key:
    files:
      - poetry.lock
      - pyproject.toml
  paths:
    - .cache/pip
    - .tox
